name: LINUX HVM3 CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  hvml-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Cache GHC and Cabal installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.ghcup
            ~/.cabal
          key: linux-ghc-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('cabal.project*') }}
          restore-keys: |
            linux-ghc-
            
      - name: Set up GHC and Cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.12.1'
          cabal-version: '3.14.1.1'
          
      - name: Update Cabal package list
        run: cabal update
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev
          
      - name: Cache Cabal store
        uses: actions/cache@v3
        with:
          path: ~/.cabal/store
          key: linux-cabal-store-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('cabal.project*') }}
          restore-keys: |
            linux-cabal-store-
            
      - name: Build the project
        run: cabal build
        
      - name: Lazy - Run interpreted normalization
        run: cabal run hvml -- run ./book/feat_hoas.hvml -s
        
      - name: Lazy - Run compiled normalization
        run: cabal run hvml -- run ./book/feat_hoas.hvml -c -s
        
      - name: Lazy Run interpreted collapse
        run: cabal run hvml -- run ./book/enum_lam_smart.hvml -C -s
        
      - name: Lazy - Run compiled collapse
        run: cabal run hvml -- run ./book/enum_lam_smart.hvml -C -c -s

      - name: Strict - Run interpreted normalization
        run: cabal run hvml -- run ./book/bench_parallel_sum_range.hvms -s
